// Editorial bundles, not a count of independent modules or a delivery promise.
// References are physical PDF pages in the revised source dated 2026-09-10.
export const SOURCE = {date:'10. September 2026', pages:209,
  path:'C:/Users/info/Documents/KAVEO Konzept/output/pdf/KAVEO_Konzept_und_Funktionsablaeufe.pdf',
  sha256:'3927ed4102ab4470d61ac10719cdc846d32fc9ba3f96a40ee4857ecbe04482fe'};

export const PACKAGES = [
  {id:'A',title:'Gemeinsam eine Runde spielen.',name:'Startpaket',when:'Zuerst vorgesehen',lane:'start',pages:[22,23,24,25],
    summary:'Einladen, verabreden, Scores festhalten und auf die Runde zurückblicken. Ein klarer erster Nutzen für bestehende Spielgruppen.',
    points:['Profil und Sichtbarkeit bewusst wählen. Golf-Grundlagen und lokale Einstiegsmöglichkeiten finden.',
      'Eine gemeinsame Runde mit Platz, Termin und Mitspielern planen. Zusagen von bestätigten Startzeiten unterscheiden.',
      'Scores manuell eingeben, berichtigen und bei fehlender Verbindung lokal zwischenspeichern.',
      'Die Gruppen-Scorekarte prüfen, privat zurückblicken und Ergebnisse gezielt teilen.'],
    boundary:'Der erste Ablauf soll ohne Geräteautomatik, DGV-Anbindung oder umfassende Clubsoftware funktionieren.'},
  {id:'B',title:'Aus einer Runde wird die nächste.',name:'Dranbleiben',when:'Danach vorgesehen',lane:'core',pages:[24,26],
    summary:'Runden, Verabredungen und Lernschritte wieder aufgreifen, statt jedes Mal neu anzufangen.',
    points:['Rundenarchiv und einfache Statistiken aus tatsächlich erfassten Daten.',
      'Favoriten, Kalender und selbst steuerbare Hinweise.',
      'Kleine private Ligen, Terminreihen und Freundesformate.',
      'Ein kurzer Lernpfad für Einstieg, Platzreife und die erste Runde.'],
    boundary:'Private Aufzeichnungen und Gruppenwertungen sind keine offiziellen Handicap- oder Turnierergebnisse.'},
  {id:'C',title:'Mit echten Angeboten verbinden.',name:'Partnerpiloten',when:'Mit wenigen Partnern erproben',lane:'pilot',pages:[24,27],
    summary:'Clubs, Trainer und Indooranlagen zunächst mit überschaubaren Abläufen einbeziehen.',
    points:['Clubprofil, gepflegtes Angebot und eine nachvollziehbare Anfrage oder Buchungsbestätigung.',
      'Trainerprofil, Kurs oder Übung, Termin und kurze Nachbereitung.',
      'Indoorangebot mit passender Box, Zeitraum, Preis und klarem Buchungsstatus.'],
    boundary:'Partner, Pilotgebiet und konkrete Datenwege sind noch festzulegen. Es werden keine bestehenden Kooperationen behauptet.'},
  {id:'D',title:'Mehr Möglichkeiten auf dem Platz.',name:'Spieler-Ausbau',when:'Nach erprobtem Grundangebot',lane:'core',pages:[24,25],
    summary:'Die Rundenbegleitung erweitern, wenn sich der erste gemeinsame Ablauf im Alltag bewährt.',
    points:['GPS und verlässliche Informationen zu den Spielbahnen.',
      'Weitere Spielmodi und umfangreichere private Turniere.',
      'Papier-Scorekarten übernehmen und erkannte Werte prüfen.',
      'Video- und Medienwerkzeuge für Spiel, Training und Rückblicke.'],
    boundary:'Aus Umfang und Reihenfolge folgt noch kein Veröffentlichungstermin.'},
  {id:'E',title:'Werkzeuge für den Golfbetrieb.',name:'Betriebssysteme',when:'Eigene Entwicklungslinie',lane:'business',pages:[9,24,27,30,35,50],
    summary:'Umfassende Club- und Anlagenorganisation braucht einen eigenen Ausbau neben der Spieler-App.',
    points:['Timetable, Startzeiten, Tarife, Sperrungen und Online-Check-in.',
      'Live-Platzkarte mit Datenalter und gezielter Kommunikation.',
      'Kasse, Warenwirtschaft, Rangebetrieb und Vermietungen.',
      'Rollen, Zuständigkeiten und definierte Schnittstellen.'],
    boundary:'Diese Betriebslinie ist kein Pflichtschritt für das Startpaket und keine Zusage eines fertigen Clubsystems.'},
  {id:'F',title:'Technik, der man vertrauen kann.',name:'Geräte, Verband und KI',when:'Nach Qualitäts- und Partnerprüfung',lane:'dependency',pages:[15,24,28,36,42,49],
    summary:'Automatik und externe Daten erst dann einbeziehen, wenn Qualität, Freigaben und Korrekturwege geklärt sind.',
    points:['Schlagerkennung über unterstützte Geräte und nachvollziehbare Schlägerempfehlungen.',
      'Smartwatch-, Simulator- und Messdatenanbindungen.',
      'Mögliche DGV-Prozesse über autorisierte Datenwege.',
      'Prüfbare KI-Hilfen für Regeln, Analyse und Trainingsnachbereitung.'],
    boundary:'Gewünschte Anbindungen sind keine zugesagten Zugänge. Automatische Vorschläge bleiben korrigierbar.'},
  {id:'G',title:'Die Golfwelt weiter öffnen.',name:'Vergleich und Reichweite',when:'Späterer Ausbau',lane:'market',pages:[12,13,24,51,59,61,62],
    summary:'Ausrüstung, Reisen, Inhalte und passende Partner in den Golfalltag einbinden.',
    points:['Händlerangebote und Golfreisen auffindbar und vergleichbar machen.',
      'Marken, Sponsoren und Creator im passenden Zusammenhang einbeziehen.',
      'Kooperations- und Veröffentlichungswerkzeuge weiter ausarbeiten.',
      'Weitergehende Medienformate bis zum Livestreaming prüfen.'],
    boundary:'Käufe und Reisebuchungen werden beim jeweiligen Anbieter abgeschlossen. KAVEO verkauft die Produkte und Reisen nicht selbst.'}
];

const feature=(id,title,summary,points,pages,note='',kind='planned')=>({id,title,summary,points,pages,note,kind});
export const AREAS = [
  {id:'entdecken',title:'Entdecken und Lernen',short:'Entdecken & Lernen',intro:'Vom ersten Interesse bis zu einer gut vorbereiteten ersten Runde.',features:[
    feature('golf-verstehen','Golf verständlich kennenlernen','Spiel, Platz und Ausrüstung ohne Vorwissen verstehen.',
      ['Texte und Videos zum Spielziel und zum Aufbau einer Runde.','Begriffe direkt erklären und passende nächste Schritte anbieten.'],[3,76,79]),
    feature('regeln-einstieg','Regeln, Etikette und Sicherheit','Typische Situationen auf dem Platz verständlich einordnen.',
      ['Ein Nachschlagewerk mit kurzen Erklärungen und Beispielen.','Sicherheit, Rücksichtnahme und Verhalten auf der Anlage.','Inhalte für Kursvorbereitung und die ersten eigenen Besuche.'],[3,26,79]),
    feature('lernweg','Dein persönlicher Lernweg','Lernen dort fortsetzen, wo du zuletzt aufgehört hast.',
      ['Golfstart, erste Übungen und Lernfortschritt zusammenführen.','Passende Inhalte zum Erfahrungsstand finden und wieder aufgreifen.','Vorbereitung auf Platzreife und selbstständiges Spielen.'],[26,57,78,80,81]),
    feature('erste-runde','Die erste Runde vorbereiten','Mit mehr Orientierung auf den Platz gehen.',
      ['Vorbereitungshilfen und eine Checkliste für den ersten Platzbesuch.','Übungsmöglichkeiten und passende Trainingspartner entdecken.','Den Weg vom Schnuppern über den Kurs bis zur eigenen Runde erklären.'],[3,57,78,80,81],
      'Kurs- und Zugangsvoraussetzungen legt die jeweilige Anlage fest.'),
    feature('kosten-ausruestung','Kosten und erste Ausrüstung','Einordnen, was du brauchst und was zusätzlich kosten kann.',
      ['Kurs, Training, Mitgliedschaft, Greenfee und Ausrüstung getrennt betrachten.','Einmalige und laufende Ausgaben verständlich machen.','Leihen, Gebrauchtkauf und Grundausstattung erklären.'],[78,79],
      'Fehlende Preise bleiben offen; eine Orientierung ersetzt kein individuelles Fitting.')
  ]},
  {id:'planen',title:'Planen und Angebote',short:'Planen & Angebote',intro:'Informationen, Termine und Angebote für deinen nächsten Golfbesuch.',features:[
    feature('anlagen','Anlagen und Clubseiten','Passende Golfmöglichkeiten in deiner Umgebung finden.',
      ['Golfplätze, Übungsanlagen und Indoorangebote mit Ort und Anfahrt.','Bilder, Kontakt, Bewertungen und Informationen zur Anlage.','Wetter und aktueller Platzstatus als Hilfe für die Besuchsplanung.','Angaben und Filter zu stufenlosen Zugängen, Wegen und Hilfsangeboten.'],[3,77,84,85],
      'Aktualität und Quelle der Angaben müssen erkennbar bleiben.'),
    feature('besuch-buchen','Startzeiten und Leistungen vor Ort','Den geplanten Besuch mit seinen Bestandteilen überblicken.',
      ['Startzeiten und Greenfee-Angebote finden.','Carts, Trolleys und Leihausrüstung reservieren.','Passende Informationen zu Gastronomie und Angeboten vor Ort.'],[3,15,34,88],
      'Anfrage, bestätigte Buchung und tatsächliche Nutzung sind unterschiedliche Zustände. Zahlungswege bleiben je Anbieter zu klären.'),
    feature('kurse','Kurse, Trainer und Indoorzeiten','Vom passenden Angebot zum nachvollziehbaren Termin.',
      ['Schnupper- und Platzreifekurse vergleichen.','Einzel- und Gruppentraining sowie Indoorboxen finden.','Leistung, Preis, Voraussetzungen, Termin und Buchungsstatus zusammen anzeigen.'],[3,10,27,57,60,67,77,78]),
    feature('kalender','Kalender und Favoriten','Den nächsten Golfbesuch leichter wieder aufgreifen.',
      ['Anlagen, Angebote und Inhalte merken.','Runden, Kurse und Training im persönlichen Kalender verbinden.','Hinweise gezielt steuern, statt unnötig benachrichtigt zu werden.','Wartelisten mit ihrem tatsächlichen Teilnahme- oder Buchungsstand unterscheiden.'],[7,24,26,86],
      'Ein gemerktes Angebot reserviert noch keinen Platz.'),
    feature('mitgliedschaft','Mitgliedschaften und digitale Karten','Leistungen vergleichen und den nächsten Schritt mit dem Club klären.',
      ['Kosten, Laufzeit und Spielrechte verschiedener Mitgliedschaften vergleichen.','Eine Mitgliedschaft beim ausgewählten Club anfragen oder beantragen.','Digitale Mitglieds- und Vorteilskarten mit Herausgeber und Gültigkeit verwalten.'],[77,78,82,83],
      'Ein Antrag ist keine Aufnahmebestätigung. Eine persönliche Karte ist kein zugesagter offizieller DGV-Ausweis.'),
    feature('equipment','Ausrüstung und Service','Produkte und passende Dienstleistungen vergleichen.',
      ['Händlerpreise und Angebote für konkrete Produktvarianten vergleichen.','Gebrauchte Ausrüstung entdecken und eigene private Angebote inserieren.','Schlägertests, Fittings und Reparaturangebote finden.'],[4,12,59,97],
      'Für einen Händlerkauf geht es zum ausgewählten Anbieter. KAVEO verkauft selbst keine Schläger; Zahlungs- und Versandwege privater Angebote bleiben offen.'),
    feature('reisen','Golfreisen und Hotels','Unterkunft und Golfprogramm im Zusammenhang planen.',
      ['Reise- und Hotelangebote entdecken und vergleichen.','Golfprogramm, Zeitraum und Mitreisende berücksichtigen.','Passende Angebote im persönlichen Reiseplan wiederfinden.'],[12,61,69,98],
      'Buchung, Bezahlung, Änderungen, Stornierung und Erstattung erfolgen beim Reiseanbieter oder Hotel.')
  ]},
  {id:'spielen',title:'Spielen und Erfassen',short:'Spielen & Erfassen',intro:'Von der gemeinsamen Rundenvorbereitung bis zu einem nachvollziehbaren Rückblick.',features:[
    feature('runde-planen','Runde und Mitspieler vorbereiten','Vor dem Abschlag klären, wer wie mitspielt.',
      ['Platz, Strecke, Abschläge und Spielmodus auswählen.','Freunde einladen und Gäste ohne eigenes Konto zur Scorekarte hinzufügen.','Einzel-, Gegeneinander- und Teamformate verständlich unterscheiden.'],[25,33,70,71],
      'Weitere Spielmodi sind dem späteren Spieler-Ausbau zugeordnet; nicht alle Varianten gehören ins Startpaket.'),
    feature('score','Manuelle Scorekarte','Ergebnisse schnell festhalten und bewusst abschließen.',
      ['Scores pro Loch, Spieler oder Team eingeben.','Fehler berichtigen und unvollständige Werte als offen kennzeichnen.','Die Runde prüfen, abschließen und die Scorekarte gezielt teilen.'],[25,33,72],
      'Persönliche Scores sind nicht automatisch offiziell anerkannte Ergebnisse.'),
    feature('rundenarchiv','Rundenarchiv, Statistik und Ziele','Aus vergangenen Runden etwas für die nächste mitnehmen.',
      ['Gespeicherte Runden wiederfinden und vergleichen.','Einfache und später detailliertere Statistiken aus vorhandenen Daten.','Persönliche Ziele und den eigenen Handicap-Verlauf betrachten.'],[4,26,33,53],
      'Fehlende Daten werden nicht ergänzt oder als Null gewertet. Der persönliche Handicap-Verlauf ersetzt keine Verbandsbestätigung.'),
    feature('gps','GPS und Entfernungen','Die aktuelle Spielbahn besser überblicken.',
      ['Kartenansicht mit Standort und Genauigkeit.','Distanzen zu Grünbereichen und verfügbaren Hindernissen.','Eigene Zielpunkte wählen und Lochzuordnungen korrigieren.'],[24,25,71,72],
      'Platzdaten und Ortung müssen verlässlich sein. Grünmitte und tatsächliche Fahnenposition sind nicht dasselbe.'),
    feature('platznotizen','Persönliche Platznotizen','Erfahrungen zu einem Platz für spätere Besuche festhalten.',
      ['Eigene Hinweise zur Anlage oder zu einzelnen Bahnen speichern.','Notizen bei der Vorbereitung und auf dem Platz wiederfinden.'],[85],
      'Eine weitergehende taktische Kartenplanung ist ein ergänzender Vorschlag.'),
    feature('golfbag','Digitales Golfbag und Schlägerhilfe','Deine Ausrüstung und persönlichen Längen einordnen.',
      ['Eigene Schläger und Schlaglängen hinterlegen.','Zielentfernung mit verfügbaren Wetter- und Windangaben verbinden.','Empfehlungen mit ihrer Datengrundlage nachvollziehen.'],[4,24,72,92],
      'Die Schlägerempfehlung ist ein später zu prüfendes Konzeptziel, keine garantierte Flugweite.'),
    feature('schlagerkennung','Handy, Uhr und automatische Erfassung','Schläge unterstützen lassen, ohne die Kontrolle abzugeben.',
      ['Unterstützte Geräte für Bewegung, Standort und Zeit einbeziehen.','Vermutete Schläge bestätigen, ergänzen oder verwerfen.','Manuelle Erfassung als Korrekturweg erhalten.'],[4,24,49,72],
      'Geräteunterstützung und Erkennungsqualität sind noch zu validieren. Ein erkannter Schwung beweist keinen Ballkontakt.'),
    feature('eigene-daten','Offline, Papier-Score und eigene Daten','Deine Aufzeichnungen auch über einen einzelnen Besuch hinaus nutzen.',
      ['Vorgesehene Offlinefunktionen und lokale Zwischenstände.','Papier-Scorekarten fotografieren, erkannte Werte prüfen und übernehmen.','Eigene Golfdaten importieren und exportieren.'],[4,25,76,98,99],
      'Lokales Speichern gehört zum Startablauf; Papiererkennung und weitergehende Datenfunktionen sind spätere Erweiterungen.')
  ]},
  {id:'trainieren',title:'Trainieren und Verbessern',short:'Trainieren & Verbessern',intro:'Übungen, Beobachtungen und Betreuung für dein eigenes Spiel zusammenhalten.',features:[
    feature('uebungen','Übungen und Trainingsplan','Gezielt üben und passende Inhalte wiederfinden.',
      ['Übungen in Text und Video für unterschiedliche Erfahrungsstände.','Persönliche Ziele, Challenges, Trainingsprogramme und Trainingstagebuch.','Durchgeführte Einheiten und den nächsten Schritt festhalten.'],[4,10,36,77,90,91,133,134]),
    feature('trainerfeedback','Trainerfeedback und Nachbereitung','Nach dem Termin an Erklärungen und Übungen anknüpfen.',
      ['Freigegebene Hinweise bei der passenden Trainingseinheit wiederfinden.','Übungen und persönliche nächste Schritte speichern.','Rückfragen im zugehörigen Trainerchat stellen.'],[10,14,27,36,55,68],
      'Private Trainernotizen bleiben von geteilten Inhalten getrennt. Ein Chat verspricht keine ständige Erreichbarkeit.'),
    feature('videoanalyse','Videoanalyse und Messdaten','Schwungaufnahmen und verfügbare Werte vergleichen.',
      ['Videos ansehen, vergleichen und mit Hinweisen ergänzen.','Messdaten mit Quelle, Gerät und Bedingungen einordnen.','Aufnahmen bewusst für Trainerfeedback freigeben.'],[10,36,55,68]),
    feature('ki-training','KI-gestützte Trainingshilfen','Aus tatsächlichen Aufnahmen einen prüfbaren Entwurf gewinnen.',
      ['Vereinbarte Aufzeichnungen aus einer Einheit auswerten lassen.','Zusammenfassungen und passende Übungen als Entwurf vorbereiten.','Dem Trainer Prüfung, Korrektur und Ergänzung ermöglichen.'],[4,10,14,24,36,68],
      'Keine erfundenen Beobachtungen und keine Zusage einer bestimmten Analysequalität.'),
    feature('regelhilfe','Verständliche Regelhilfe','Eine konkrete Golfsituation leichter einordnen.',
      ['Regeln in verständlichen eigenen Worten mit Kontext.','Eine KI-Hilfe für Fragen aus dem Golfalltag.','Unklare Fälle kenntlich machen und weiter prüfen lassen.'],[4,24,64],
      'Eine KI-Antwort ersetzt keine zuständige Entscheidung in einem ungeklärten Regelfall.')
  ]},
  {id:'community',title:'Community und Erlebnisse',short:'Community & Erlebnisse',intro:'Die Menschen, Absprachen und Erlebnisse rund um dein Golfspiel.',features:[
    feature('profil','Profil und Privatsphäre','Selbst bestimmen, was andere von dir sehen.',
      ['Ein persönliches Profil passend zur eigenen Nutzung.', 'Empfänger und Umfang beim Teilen bewusst auswählen.','Standort, Ergebnisse und Trainingsinhalte getrennt freigeben.'],[5,7,22,25,37]),
    feature('mitspieler','Freunde und Mitspieler','Bestehende Kontakte verbinden und passende Runden finden.',
      ['Freunde wiederfinden und erneut zum Spielen einladen.','Mitspieler nach Ort, Termin und passendem Spielinteresse suchen.','Offene Plätze in gemeinsamen Runden sichtbar machen.'],[5,6,23,37,56],
      'Eine Teilnahmezusage ersetzt keine bestätigte Startzeit beim Anbieter.'),
    feature('gruppen-chat','Gruppen und Messenger','Absprachen bei der passenden Aktivität wiederfinden.',
      ['Private Gruppen, Freundeskreise und Mannschaften organisieren.','Zu Runde, Gruppe, Club oder Training kommunizieren.','Wichtige Termine und Informationen zusammenhalten.'],[5,6,7,37,68]),
    feature('turniere','Private Turniere und Ligen','Gemeinsam spielen und Wertungen nachvollziehen.',
      ['Kleine Gruppenformate und Freundesligen für wiederkehrende Runden.','Später weitere Turnierformate, Startlisten und Teamwertungen.','Laufende Ergebnisse, Prüfung und abschließende Freigabe unterscheiden.'],[4,11,24,26,58,68],
      'Kleine private Formate und umfangreiche Turnierorganisation werden schrittweise getrennt entwickelt.'),
    feature('beitraege','Beiträge und Austausch','Golfmomente mit dem passenden Publikum teilen.',
      ['Runden, Bilder, Videos und Erfahrungen veröffentlichen.','Sichtbarkeit eigener Inhalte bewusst festlegen.','Private Trainingsaufnahmen nicht automatisch öffentlich machen.'],[7,37,56,68],
      'Folgen, Kommentare, Reaktionen und Themensteuerung sind ergänzende Vorschläge, noch keine endgültigen Produktentscheidungen.'),
    feature('golfmedien','Aufnehmen und Bearbeiten','Golfaufnahmen zu einer eigenen Fassung zusammenführen.',
      ['Aufnahmehilfen, mehrere Perspektiven, Schnitt, Zeitlupe, Stabilisierung und Ton.','Untertitel, Übersetzungen, Vorlagen und Medienorganisation.','Ballfluglinien, Schwungvergleiche und Markierungen.','Highlights, Rückblicke und gemeinsame Medienprojekte vorbereiten.'],[13,24,62,69],
      'Eine Fluglinie im Video ist keine gemessene Flugbahn. Automatische Bearbeitungen sollen prüfbar und korrigierbar bleiben.'),
    feature('live-interaktiv','Livevideos und interaktive Inhalte','Gemeinsame Golfmomente und neue Medienformate ermöglichen.',
      ['Livevideos, gemeinsame Medienprojekte und Feedback zu Szenen.','Interaktive Videostellen, Lernverzweigungen und Panoramarundgänge.','Golfdaten und persönliche Rückblicke im passenden Medienkontext aufbereiten.'],[13,24,69,202,203,204,205,206,207],
      'Livestreaming gehört zum späteren Ausbau. Ein gewöhnlicher Videoexport übernimmt interaktive KAVEO-Funktionen nicht automatisch.'),
    feature('golfalltag','Familie, Mannschaft und Golfalltag','Gemeinsame Aktivitäten über eine einzelne Runde hinaus planen.',
      ['Familien- und Jugendangebote sowie Mannschaftsorganisation.','Fahrgemeinschaften und gemeinsame Aktivitäten.','Fundsachen sowie Demotage, Schlägertests, Clubfeste und weitere Golfveranstaltungen finden.'],[4,82,83,87,95,96,97],
      'Berechtigungen für Minderjährige und offizielle Nachweise benötigen eigene Klärungen.'),
    feature('community-schutz','Schutz und nachvollziehbare Hilfe','Bei unerwünschtem Kontakt selbst handeln können.',
      ['Stummschalten, Blockieren und Melden nach ihrem Zweck trennen.','Meldungen zuständig prüfen und Rückmeldungen verständlich machen.','Gruppenrechte von privaten Gesprächen und Datenfreigaben trennen.'],[5,7,8,37],
      'Die konkreten Abläufe, Regeln, Zuständigkeiten und Reaktionszeiten sind noch auszuarbeiten.','proposal')
  ]},
  {id:'partner',title:'Partner und Betrieb',short:'Partner & Betrieb',intro:'Eigene Arbeitsbereiche für die Menschen und Betriebe hinter dem Golfbesuch.',features:[
    feature('clubs','Golfclubs','Mitgliederkontakt, Spielbetrieb und kaufmännische Vorgänge verbinden.',
      ['Profile, Angebote, Mitglieder und Gäste organisieren.','Timetable, Check-in, Turniere, Ligen und Live-Platzkarte.','Beiträge, Rechnungen, Kasse, Warenwirtschaft und Einkauf.','Range, Vermietungen, Spinde, Platzpflege und Problemmeldungen.'],[9,24,35,50,54],
      'Schlanke Partnerpiloten kommen vor umfassender Betriebssoftware. Eine Platzkarte ist keine unfehlbare Ortung.'),
    feature('indoor','Indooranlagen','Von der Boxenbelegung bis zur tatsächlichen Session.',
      ['Boxen, Tarife, Pakete, Abos, Zusatzleistungen und Buchungen.', 'Ankunft, Einweisung, Zugang und Simulatorfreigabe getrennt führen.','Spontane Gäste vor Ort auch ohne KAVEO-Konto berücksichtigen.','Kasse, Kurse, Ligen, Gastronomie und Wartung.'],[10,24,27,60,67],
      'Gerätesteuerung und Messdaten hängen von den jeweiligen Zugängen und Partnern ab.'),
    feature('trainer','Golftrainer','Unterricht organisieren und Schüler weiter begleiten.',
      ['Profil, Angebote, Kalender, Schüler, Pakete und Abrechnung.','Einzel- und Gruppentraining, Pläne und Online-Coaching.','Videoanalyse, Feedback sowie private und geteilte Unterlagen.'],[10,14,27,36,55,68],
      'Werkzeuge für Trainerteams und Akademien sind zusätzliche Vorschläge.'),
    feature('veranstalter','Turnier- und Eventveranstalter','Den Wettbewerb von der Anmeldung bis zum Abschluss betreuen.',
      ['Veranstaltungsseiten, Anmeldungen und Teilnahmegebühren.','Teilnehmer, Gruppen, Startlisten, Ressourcen und Organisationsteam.','Livescoring, Scoreprüfung, Siegerehrung und Nachbereitung.','Chat, Sponsoren und die Abstimmung mit der Anlage.'],[11,58,68],
      'Eine mögliche offizielle Ergebnisübermittlung setzt eine eingerichtete, autorisierte Schnittstelle voraus.'),
    feature('haendler','Händler und Golfservices','Angebote dort sichtbar machen, wo Golfer Ausrüstung suchen.',
      ['Produkt- und Angebotsdaten sowie Filialinformationen pflegen.','Verfügbarkeit, Kontakt und Serviceangebote zusammenführen.','Anfragen und Auswertungen im Anbieterbereich betrachten.'],[12,59,66,69],
      'Die Händleroberfläche ist ein ergänzender Vorschlag. Der Kauf bleibt beim Händler.','proposal'),
    feature('reiseanbieter','Reiseanbieter und Golfhotels','Golfprogramme und Unterkünfte verständlich vergleichbar machen.',
      ['Anbieterprofile und nachvollziehbare Reise- und Hotelangebote.','Leistungen, Konditionen und Gruppenwünsche vergleichen.','Kontakt, Planung und Rückmeldungen im richtigen Zusammenhang.'],[12,61,66,69],
      'Die Anbieteroberfläche ist vorgeschlagen. Buchung, Zahlung und Vertragsabwicklung bleiben beim Anbieter.','proposal'),
    feature('marken','Marken und Hersteller','Produkte, Testgelegenheiten und Ansprechpartner verbinden.',
      ['Markenprofile, Produktkataloge und Unterlagen.','Tests, Service, Schulungen und Rückmeldungen.','Händler-, Trainer- und Creator-Kooperationen.'],[11,63,66],
      'Eigene Herstelleroberflächen und diese weitergehenden Abläufe sind ergänzende Vorschläge.','proposal'),
    feature('verbaende','Verbände und offizielle Datenwege','Bestätigte Vorgänge über passende Schnittstellen verbinden.',
      ['Eine DGV-Anbindung und direkte Ergebnisübermittlung durch Clubs als Konzeptziele.','Benötigte Zugänge, erlaubten Umfang und Rückmeldungen je Datenweg klären.','Weitere Verbandsinformationen, Wettbewerbe, Lehrgänge und Nachwuchsangebote prüfen.'],[11,15,24,44,64],
      'Der weitergehende Verbandsbereich ist ein Vorschlag. Es gibt hier keine Zusage einer bestehenden DGV-Anbindung.'),
    feature('sponsoren','Sponsoren und Kooperationen','Engagements im passenden Golfkontext organisieren.',
      ['Passende Club-, Turnier- oder Inhaltsformate finden.','Leistungen, Vereinbarungen und Materialien abstimmen.','Kennzeichnung und Nachweise zu vereinbarten Platzierungen betrachten.'],[13,65,69],
      'Ein eigener Sponsorenbereich ist vorgeschlagen. Reichweite und Wirkung werden nicht versprochen.','proposal'),
    feature('creator','Creator und Veröffentlichungen','Medienprojekte und Kooperationen im Zusammenhang führen.',
      ['Projekte, Mediathek und Veröffentlichungsvorbereitung.','Zusammenarbeit, Feedback und erforderliche Freigaben.','Weitergehende Creator-Verwaltung, Kooperationen und exklusive Angebote.'],[13,62,66,69],
      'Die Medienwerkzeuge sind Konzeptideen; die weitergehende Creator-Verwaltung bleibt ein Vorschlag.','proposal'),
    feature('schnittstellen','Eigene Schnittstellen und Partnerdaten','KAVEO mit passenden Systemen verbinden.',
      ['Eigene Schnittstellen für Clubs und Indooranlagen.','Datenzugänge zu Verband, Messgeräten und weiteren Partnersystemen klären.','Zweck, Datenquelle und unterstützten Umfang jeder Anbindung unterscheiden.'],[15,44,99,107,189],
      'Eine eigene Schnittstelle erteilt keinen Zugang zu einem fremden System.'),
    feature('plattform','Gemeinsame Grundlagen','Verlässlichkeit und Zugriffsrechte über alle Bereiche hinweg.',
      ['Rollen und Organisationen mit passenden Berechtigungen.', 'Datenquellen, Aktualität, Freigaben und Korrekturwege.','Nutzerhilfe, Anbieteraufnahme, Datenpflege und Moderation.','Zugängliche App-Bedienung und weitergehende Offline-Abläufe.'],[189,190,191,192,193,207,208,209],
      'Diese übergreifenden Ausarbeitungen sind Vorschläge. Konkrete Zahlungsmodelle und rechtliche Detailregeln bleiben ebenfalls zu klären.','proposal')
  ]}
];

export const AREA_IDS=AREAS.map(area=>area.id);
export function areaForHash(hash){
  const id=String(hash||'').replace(/^#/,'');
  return AREAS.find(area=>id==='bereich-'+area.id||area.features.some(item=>id==='funktion-'+item.id))?.id??null;
}
